### ISSUE TITLE
Exception: TypeError: Cannot read property '1280' of undefined

### ISSUE THREAD

**Issue by tomgco** [numo-labs/lambda-ne-classic-package-provider#86]
2016-06-07T15:37:30.871Z	bcdeb48b-2cc5-11e6-8ea1-ebbe2cfbc878	TypeError: Cannot read property '1280' of undefined
    at map_large_hotel_images (/var/task/lib/result_mapper.js:27:27)
    at /var/task/lib/result_mapper.js:111:22
    at Array.map (native)
    at Object.map_ne_result_to_graphql (/var/task/lib/result_mapper.js:96:23)
    at /var/task/lib/api_request.js:116:38
    at /var/task/lib/api_request.js:62:16
    at IncomingMessage.<anonymous> (/var/task/lib/http_request.js:28:14)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)

**Comment by nelsonic** [comment]
@tomgco thanks *very* much for reporting this! 👍 
I am investigating now and will PR *shortly*.

**Comment by nelsonic** [comment]
*Found* the **Two** hotels that don't have images:
```js
{ wvId: 148726,
  caId: 67852,
  name: 'Knightsbridge Green',
  description: 'Situated in the heart of Knightsbridge around the corner from London\'s well known department stores Harrods and Harvey Nichols. Located on the street leading to Kensington High Street, across the road to Hyde Park. Close South Kensington with all its Museums.The nearest underground station is Knightsbridge on the Piccadilly Line, only 1 minute walk.\n\n\nThe hotel does not have a restaurant, but they will serve you with a freshly prepared Continental breakfast to your room.\n\n\nThe hotel does not have a lobby, just a check-in desk and a sitting room with TV and leather sofas, as soon as you walk in on the left.\n\n\nA great location in the heart of Knightsbridge, ideal for guests travelling both for business and pleasure, shopping and sight seeing. Breakfast is served in the rooms as the hotel does not have a breakfast room. (0610AB)',
  rating: { guestRating: 0, doubledRating: 7 },
  geographical:
   { countryId: 206,
     countryName: 'Storbritannien',
     resortId: 588,
     resortName: 'London' },
  location: { latitude: 51.50152, longitude: -0.162526 },
  url: 'http://www.spies.dk/storbritannien/london/knightsbridge-green',
  images: [],
  facts:
   [ { id: 'LolloAndBernie', name: 'Lollo och Bernie', value: false },
     { id: 'IsAdultHotel', name: 'Adult hotel', value: false },
     { id: 'AllInclusive', name: 'All Inclusive', value: false } ],
  hotelProduct: { id: 52, key: 'Ordinary' },
  interestProducts: [],
  importUpdateId: '2016-06-07T16:18:32.966Z' },
{ wvId: 198243,
  caId: 99845,
  name: 'St George Residence All Suite Hotel Deluxe',
  description: '',
  rating: { guestRating: 0, doubledRating: 4294967295 },
  geographical:
   { countryId: 90,
     countryName: 'Ungarn',
     resortId: 352,
     resortName: 'Budapest' },
  location: { latitude: 0, longitude: 0 },
  url: 'http://www.spies.dk/ungarn/budapest/st-george-residence-all-suite-hotel-deluxe',
  images: [],
  facts:
   [ { id: 'LolloAndBernie', name: 'Lollo och Bernie', value: false },
     { id: 'IsAdultHotel', name: 'Adult hotel', value: false },
     { id: 'AllInclusive', name: 'All Inclusive', value: false } ],
  hotelProduct: { id: 52, key: 'Ordinary' },
  interestProducts: [],
  importUpdateId: '2016-06-07T16:18:32.966Z' }
```
