### ISSUE TITLE
Exception: TypeError: Cannot read property 'forEach' of undefined > parse_sns.js:32:23

### ISSUE THREAD

**Issue by tomgco** [numo-labs/lambda-ne-classic-package-provider#87]
2016-06-07T15:32:42.208Z	eee33aae-2cc4-11e6-9bff-8d11fc066811	TypeError: Cannot read property 'forEach' of undefined
    at extract_search_params (/var/task/lib/parse_sns.js:32:23)
    at exports.handler (/var/task/index.js:17:16)

**Comment by nelsonic** [comment]
This is because the UI is not sending a list of passengers ... 😢 
I'm adding a test for it. :
